---
abstract: 'Create a Venn diagram using GD.'
author:
  - 'Djibril Ousmanou <djibel@cpan.org>'
build_requires:
  GD: 2.43
  GD::Graph: 1.44
  GD::Text::Align: 0
  List::Compare: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Venn-Chart
provides:
  Venn::Chart:
    file: lib/Venn/Chart.pm
    version: 1.01
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
